#!/usr/bin/env bash
set -euo pipefail

# Select the iOS capabilities shipped by a build. CarPlay is opt-in because
# com.apple.developer.carplay-audio is a restricted Apple entitlement.
# The default build and CI remain CarPlay-free; only a locally authorised App
# ID should run `make configure-carplay`.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS_DIR="$REPO_ROOT/ios"
CONFIG_DIR="$IOS_DIR/Config"
GENERATED_DIR="$CONFIG_DIR/Generated"
OVERLAY_XCCONFIG="$CONFIG_DIR/CarPlay.local.xcconfig"

BASE_INFOPLIST="$CONFIG_DIR/Info.plist"
BASE_ENTITLEMENTS="$CONFIG_DIR/KumoneIOS.entitlements"
CARPLAY_INFOPLIST="$GENERATED_DIR/Info-CarPlay.plist"
CARPLAY_ENTITLEMENTS="$GENERATED_DIR/KumoneIOS-CarPlay.entitlements"

PLISTBUDDY=/usr/libexec/PlistBuddy
CARPLAY=0

while [ $# -gt 0 ]; do
  case "$1" in
    --carplay) CARPLAY=1 ;;
    --no-carplay) CARPLAY=0 ;;
    -h|--help)
      sed -n '1,16p' "${BASH_SOURCE[0]}"
      exit 0
      ;;
    *)
      echo "error: unknown argument '$1'" >&2
      exit 2
      ;;
  esac
  shift
done

generate_carplay_overlay() {
  mkdir -p "$GENERATED_DIR"
  cp "$BASE_INFOPLIST" "$CARPLAY_INFOPLIST"

  "$PLISTBUDDY" \
    -c "Add :UISupportsCarPlay bool true" \
    -c "Add :UIApplicationSceneManifest dict" \
    -c "Add :UIApplicationSceneManifest:UIApplicationSupportsMultipleScenes bool true" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations dict" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication array" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication:0 dict" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication:0:UISceneConfigurationName string CarPlay" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication:0:UISceneClassName string CPTemplateApplicationScene" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication:0:UISceneDelegateClassName string \$(PRODUCT_MODULE_NAME).CarPlaySceneDelegate" \
    "$CARPLAY_INFOPLIST" >/dev/null

  cp "$BASE_ENTITLEMENTS" "$CARPLAY_ENTITLEMENTS"
  "$PLISTBUDDY" \
    -c "Add :com.apple.developer.carplay-audio bool true" \
    "$CARPLAY_ENTITLEMENTS" >/dev/null

  # This file is intentionally untracked and is picked up by Shared.xcconfig
  # with #include?. Running make configure removes it again.
  cat > "$OVERLAY_XCCONFIG" <<'EOF'
// Generated by Scripts/configure-ios.sh --carplay. Do not commit.
KUMONE_INFOPLIST_FILE = Config/Generated/Info-CarPlay.plist
KUMONE_ENTITLEMENTS_FILE = Config/Generated/KumoneIOS-CarPlay.entitlements
EOF
}

if [ "$CARPLAY" -eq 1 ]; then
  generate_carplay_overlay
  echo "Configured Moumusic iOS with CarPlay enabled."
  echo "The App ID and provisioning profile must have Apple CarPlay Audio approval."
  echo "Run 'make configure' to return to the default CarPlay-free build."
else
  rm -f "$OVERLAY_XCCONFIG"
  rm -rf "$GENERATED_DIR"
  echo "Configured Moumusic iOS (default: CarPlay disabled)."
fi
